name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.20]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: composer install --no-dev --ignore-platform-reqs

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        yarn
        yarn build

    - name: Upload the build output
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: build/

    - name: Download the build output
      uses: actions/download-artifact@v2
      with:
        name: build-output

    - name: Display structure
      run: ls -R

    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: simple-floating-contact-form
        BUILD_DIR: ./build

        name: Deploy to WordPress.org