name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.20]

    steps:
    - uses: actions/checkout@v3

    - name: Display structure
      run: ls -R

    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: simple-floating-contact-form
        BUILD_DIR: ./build